blank_issues_enabled: false
contact_links:
  - name: Mod Description
    url: https://www.nexusmods.com/mysummercar/mods/203?tab=description
    about: Please make sure to read the full mod description before submitting anything.
    
  - name: Discussion page
    url: https://github.com/tiagomarked/CallYourCousin/discussions
    about: Please ask and answer questions here.
  
